language: perl

before_install:
  - sudo apt-get install gfortran

install:
  - cpanm -n --installdeps -v .

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"

script:
  - perl Build.PL
  - ./Build --verbose
  - ./Build test --verbose

env:
  global:
    - PERL_USE_UNSAFE_INC=0
  matrix:
    - FFI_PLATYPUS=1
    - FFI_PLATYPUS_DEBUG_FAKE32=1

