language: perl

before_install:
  - sudo apt-get install gfortran

install:
  - cpanm -n FFI::Platypus
  - cpanm -n File::Which
  - cpanm -n Capture::Tiny

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"

script:
  - perl Build.PL
  - ./Build --verbose
  - ./Build test --verbose

env:
  - FFI_PLATYPUS=1
  - FFI_PLATYPUS_DEBUG_FAKE32=1
  - FFI_PLATYPUS_NO_ALLOCA=1
  - FFI_PLATYPUS_DEBUG_FAKE32=1 FFI_PLATYPUS_NO_ALLOCA=1

