---
abstract: 'Documentation and tools for using Platypus with Fortran'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  FFI::CheckLib: '0'
  File::Which: '0'
  Module::Build: '0.38'
  Module::Build::FFI: '0.22'
configure_requires:
  File::Which: '0'
  Module::Build: '0.38'
  Module::Build::FFI: '0.22'
dynamic_config: 1
generated_by: 'Module::Build version 0.4211, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: FFI-Platypus-Lang-Fortran
provides:
  FFI::Platypus::Lang::Fortran:
    file: lib/FFI/Platypus/Lang/Fortran.pm
    version: '0.06'
  Module::Build::FFI::Fortran:
    file: lib/Module/Build/FFI/Fortran.pm
    version: '0.06'
  Module::Build::FFI::Fortran::ExtUtilsF77:
    file: lib/Module/Build/FFI/Fortran/ExtUtilsF77.pm
    version: '0.06'
requires:
  FFI::Platypus: '0.22'
  File::Which: '0'
  Module::Build::FFI: '0.22'
  perl: '5.008001'
resources:
  license: http://dev.perl.org/licenses/
version: '0.06'
